---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    semver: '>1.0.0'
  url: https://github.com/kyverno/kyverno

